import type { Project, ResumeData } from './types';

export const projectsData: Project[] = [
  {
    id: '1',
    title: 'DeFi Staking Platform',
    description: 'A decentralized finance (DeFi) platform for staking crypto assets, built with Next.js, Solidity, and Ethers.js.',
    imageUrl: 'https://picsum.photos/seed/web3/600/400',
    imageHint: 'web3 blockchain',
    tags: ['Next.js', 'Solidity', 'Ethers.js', 'Hardhat', 'Tailwind CSS', 'Web3'],
    liveUrl: '#',
    repoUrl: '#',
  },
  {
    id: '2',
    title: 'AI Meme Generator',
    description: 'A fun application that uses AI to generate memes based on user input and trending templates.',
    imageUrl: 'https://picsum.photos/seed/meme-ai/600/400',
    imageHint: 'meme generator',
    tags: ['Python', 'Flask', 'React', 'AI/ML', 'Docker', 'JavaScript'],
    liveUrl: '#',
  },
  {
    id: '3',
    title: 'Cloud IDE Environment',
    description: 'A browser-based Integrated Development Environment for coding on the go, leveraging cloud infrastructure.',
    imageUrl: 'https://picsum.photos/seed/code-editor/600/400',
    imageHint: 'code editor',
    tags: ['Node.js', 'React', 'TypeScript', 'WebSockets', 'Docker', 'AWS'],
    repoUrl: '#',
  },
  {
    id: '4',
    title: 'Retro Game Emulator',
    description: 'A web-based emulator for classic computer games, written in Rust and compiled to WebAssembly.',
    imageUrl: 'https://picsum.photos/seed/computer-game/600/400',
    imageHint: 'retro gaming',
    tags: ['Rust', 'WebAssembly', 'JavaScript', 'HTML5 Canvas'],
    liveUrl: '#',
    repoUrl: '#',
  },
];

export const resumeData: ResumeData = {
  summary: "A highly motivated and results-oriented Full Stack Developer with 5+ years of experience in designing, developing, and deploying web applications. Proficient in JavaScript, React, Node.js, and various cloud technologies. Passionate about creating intuitive user experiences and solving complex problems.",
  experience: [
    {
      id: 'exp1',
      title: 'Senior Software Engineer',
      company: 'Tech Solutions Inc.',
      period: 'Jan 2021 - Present',
      description: [
        'Led a team of 5 developers in agile sprints to deliver key features for a SaaS product.',
        'Architected and implemented microservices using Node.js and Docker, improving scalability by 30%.',
        'Mentored junior engineers and conducted code reviews to ensure code quality and consistency.',
      ],
    },
    {
      id: 'exp2',
      title: 'Full Stack Developer',
      company: 'Web Wizards LLC',
      period: 'Jun 2018 - Dec 2020',
      description: [
        'Developed and maintained client websites using React, Angular, and Vue.js.',
        'Collaborated with designers to translate mockups into responsive and interactive web pages.',
        'Integrated third-party APIs for payment processing, social media, and analytics.',
      ],
    },
  ],
  education: [
    {
      id: 'edu1',
      title: 'Master of Science in Computer Science',
      institution: 'University of Advanced Technology',
      period: '2016 - 2018',
      description: ['Specialized in Web Development and Distributed Systems.', 'Thesis on optimizing real-time data synchronization.'],
    },
    {
      id: 'edu2',
      title: 'Bachelor of Science in Software Engineering',
      institution: 'State Engineering College',
      period: '2012 - 2016',
      description: ['Graduated with Honors.', 'Active member of the coding club.'],
    },
  ],
  skills: [
    'JavaScript (ES6+)',
    'TypeScript',
    'React',
    'Next.js',
    'Node.js',
    'Express.js',
    'Python',
    'Django',
    'Rust',
    'Solidity',
    'SQL (PostgreSQL, MySQL)',
    'NoSQL (MongoDB, Firebase)',
    'RESTful APIs',
    'GraphQL',
    'WebSockets',
    'Docker',
    'Kubernetes',
    'AWS',
    'Web3.js / Ethers.js',
    'Git',
    'Agile Methodologies',
    'Problem Solving',
  ],
  downloadUrl: '/resume.pdf', // Replace with actual PDF path
};
